### ISSUE TITLE
segfault if CONFIRM_MODULE_LOAD defined

### ISSUE THREAD

**Issue by starius** [dpapavas/luaprompt#6]
Uncomment the following line of Makefile:
```makefile
CFLAGS+= -DCONFIRM_MODULE_LOAD
```
Compile & run. Input some text, e.g., "b", press TAB. The program crashes.

```bash
$ ./luap 
Lua 5.1  Copyright (C) 1994-2012 Lua.org, PUC-Rio
luap 0.5 Copyright (C) 2012-2014 Dimitris Papavasiliou

>  bSegmentation fault
```

Backtrace:

```
>  b
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7773690 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
(gdb) bt
#0  0x00007ffff7773690 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#1  0x00007ffff7767dbc in lua_next () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
#2  0x000000000040393b in module_completions (text=0x660940 "b", state=0) at prompt.c:432
#3  0x00000000004041fa in generator (text=0x660940 "b", state=0) at prompt.c:659
#4  0x00007ffff7bb3cb0 in rl_completion_matches () from /lib/x86_64-linux-gnu/libreadline.so.6
#5  0x00007ffff7bb4894 in rl_complete_internal () from /lib/x86_64-linux-gnu/libreadline.so.6
#6  0x00007ffff7baba50 in _rl_dispatch_subseq () from /lib/x86_64-linux-gnu/libreadline.so.6
#7  0x00007ffff7bac032 in readline_internal_char () from /lib/x86_64-linux-gnu/libreadline.so.6
#8  0x00007ffff7bac535 in readline () from /lib/x86_64-linux-gnu/libreadline.so.6
#9  0x0000000000406b3a in luap_enter (L=0x608010) at prompt.c:1391
#10 0x0000000000402d13 in main (argc=1, argv=0x7fffffffe308) at luap.c:234
(gdb) 
```

**Comment by dpapavas** [comment]
Thanks for pointing this out!  It seems that Lua 5.1 has package.loaders where 5.2 has package.searchers with similar functionality.  I didn't notice that.  For our purposes I think that simply changing the key name based on version should be enough.  Please check out the wip branch and confirm that it fixes the problem.

**Comment by starius** [comment]
The problem is fixed in branch wip.
